name: GitHub Actions Demo
on: [push]
//activation sur pull request vers la branche main
//push sur la branche main

jobs:
  TestApplication:
    runs-on: ubuntu-latest
    steps:
      - name: Récuperation du repository
        uses: actions/checkout@v2
      - name: Liste des fichiers
        run: ls
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: commande de test
        run: mvn test
      - name: Effectuer le cas de test
        run: mvn -Dtest=CalculatriceTest test




